
###CREATE
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "title": "Product 3",
    "price": 2000
}

###READ
GET http://localhost:3000/api/products/

###READ BY ID
GET http://localhost:3000/api/products/6155aba063408f3a736b6517

###UPDATE
PATCH http://localhost:3000/api/products/6155aba063408f3a736b6517
Content-Type: application/json

{
    "title": "Product 2 Updated",
    "price": 3000
}

###DELETE
DELETE http://localhost:3000/api/products/6155aba063408f3a736b6517

